# Generated by Django 6.1.1 on 2026-09-08 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khata_app', '0002_customer_khatachit_chititem'),
    ]

    operations = [
        migrations.AddField(
            model_name='khatachit',
            name='ocr_processed_at',
            field=models.DateTimeField(blank=True, help_text="When the OCR pipeline last ran on this chit's image.", null=True),
        ),
        migrations.AddField(
            model_name='khatachit',
            name='ocr_raw_text',
            field=models.TextField(blank=True, help_text='Raw text extracted by the OCR pipeline, before human review.'),
        ),
    ]
