# Generated by Django 6.1.1 on 2026-09-08 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khata_app', '0003_khatachit_ocr_processed_at_khatachit_ocr_raw_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='chititem',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="What you paid for this item (optional) — used to estimate profit. Leave blank if you don't track this.", max_digits=10, null=True),
        ),
    ]
