# Generated by Django on 2026-09-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khata_app', '0004_chititem_cost_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='chititem',
            name='is_paid',
            field=models.BooleanField(default=False, help_text='Only meaningful when is_credit is True. Marks a credit entry as settled.'),
        ),
        migrations.AddField(
            model_name='chititem',
            name='paid_at',
            field=models.DateTimeField(blank=True, help_text='When the customer settled this credit item.', null=True),
        ),
    ]
