# Generated by Django 6.1.1 on 2026-09-22 22:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khata_app', '0005_chititem_is_paid_chititem_paid_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='khatachit',
            name='chit_type',
            field=models.CharField(choices=[('customer', 'Customer (Sale / Udhar)'), ('seller', 'Seller / Supplier (Purchase)')], default='customer', help_text='Whether this chit is from a customer sale or a seller purchase.', max_length=20),
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shopkeeper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sellers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='khatachit',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='khata_chits', to='khata_app.seller'),
        ),
    ]
