# Generated by Django 6.1.1 on 2026-10-04 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khata_app', '0006_khatachit_chit_type_seller_khatachit_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chititem',
            name='is_credit',
            field=models.BooleanField(db_index=True, default=False, help_text='Checked if this item was given on credit rather than paid for immediately.'),
        ),
        migrations.AlterField(
            model_name='chititem',
            name='is_paid',
            field=models.BooleanField(db_index=True, default=False, help_text='Only meaningful when is_credit is True. Marks a credit entry as settled.'),
        ),
        migrations.AlterField(
            model_name='chititem',
            name='paid_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When the customer settled this credit item.', null=True),
        ),
        migrations.AlterField(
            model_name='khatachit',
            name='chit_type',
            field=models.CharField(choices=[('customer', 'Customer (Sale / Udhar)'), ('seller', 'Seller / Supplier (Purchase)')], db_index=True, default='customer', help_text='Whether this chit is from a customer sale or a seller purchase.', max_length=20),
        ),
        migrations.AlterField(
            model_name='khatachit',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='chititem',
            index=models.Index(fields=['chit', 'is_credit', 'is_paid'], name='khata_app_c_chit_id_e04860_idx'),
        ),
        migrations.AddIndex(
            model_name='chititem',
            index=models.Index(fields=['is_credit', 'is_paid'], name='khata_app_c_is_cred_491015_idx'),
        ),
        migrations.AddIndex(
            model_name='khatachit',
            index=models.Index(fields=['shopkeeper', 'upload_date'], name='khata_app_k_shopkee_5eca0c_idx'),
        ),
        migrations.AddIndex(
            model_name='khatachit',
            index=models.Index(fields=['shopkeeper', 'chit_type'], name='khata_app_k_shopkee_e1e3c7_idx'),
        ),
    ]
